baseURL: 'kawhan.github.io'
title: WTF-Kawhan
theme: wtf-theme
license: MIT
licenselink: 'https://github.com/kawhan/kawhan.github.io/blob/main/LICENSE'
description: 'Kawhan?!? A documentary about a nerd who likes programming'
homepage: 'kawhan.github.io'
defaultContentLanguage: 'en'
paginate: 10
hasCJKLanguage: false
copyright: "2024 Kawhan - All rights reserved"
Author:
  name: "Kawhan Laurindo de Lima"
  email: "kawhanlaurindo@outlook.com"
menu:
  main:
    - name: Blog
      url: /blog
      weight: 1
    - name: Tags
      url: /tags
      weight: 2
    - name: Archive
      url: /archives
      weight: 3
    - name: About
      url: /about
      weight: 4
params:
  brand: HOME
  avatarURL: /images/avatar.png
  author: Kawhan
  authorDescription: Kawhan?!? A documentary about a nerd who likes programming
  info: I build things and share it.
  favicon: /images/avatar.png
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
    showMetaTags: true
  darkModeTheme: data-dark-mode
  sponsors:
    buyMeACoffee:
      enable: false
  comments:
    giscus:
      enable: true
      repo: Kawhan/kawhan.github.io
      repo_id: R_kgDOLmacvQ
      category: General
      category_id: DIC_kwDOLmacvc4CeSGX
      mapping: pathname
      position: top
      lang: en
  social:
    - name: GitHub
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: https://github.com/kawhan/kawhan.github.io'
languages:
  en:
    languageName: EN
  pt-br:
    languageName: BR
    brand: INICIO
    authorDescription: Kawhan?!? Um documentário sobre um nerd que gosta de programar
    info: Eu construo coisas e compartilho.
    menu:
      main:
        - name: Blog
          url: /blog
          weight: 1
        - name: Tags
          url: /tags
          weight: 2
        - name: Arquivos
          url: /archives
          weight: 3
        - name: Sobre
          url: /about
          weight: 4
taxonomies:
  series: series
  tag: tags
